-- CREATE TABLE students (students_id SERIAL PRIMARY KEY,
-- first_name VARCHAR (100)NOT NULL,
-- last_name VARCHAR (50) NOT NULL, 
-- birth_date DATE NOT NULL
-- )
-- Select * FROM students
-- INSERT INTO students (first_name,last_name, birth_date)
-- VALUES
-- ('Marc','Benichou','02/11/1998
-- '),
-- ('Yoan','Cohen','03/12/2010'),
-- ('Lea','Benichou','27/07/1987
-- '),
-- ('Amelia','Dux','07/04/1996
-- '),
-- ('David','Grez','14/06/2003
-- '),
-- ('Omer','Simpson','03/10/1980
-- '),
-- ('Joe','Guadie','22/10/1988')
-- Select
-- 1. Fetch all of the data from the table.
-- Select * FROM students
-- 2. Fetch all of the students first_names and last_names.
-- SELECT first_name,
-- last_name 
-- FROM students

-- 3/1. Fetch the student which id is equal to 2.
-- SELECT first_name,
-- last_name 
-- FROM students WHERE students_id = 2

--3/2. Fetch the student whose last_name is Benichou AND first_name is Marc.
-- SELECT first_name,
-- last_name 
-- FROM students WHERE last_name ='Benichou' AND
-- first_name = 'Marc'
--3/3. Fetch the students whose last_names are Benichou OR first_names are Marc.
-- SELECT first_name,
-- last_name 
-- FROM students WHERE last_name ='Benichou' OR
-- first_name = 'Marc'
--3/4. Fetch the students whose first_names contain the letter a.
-- SELECT first_name, last_name
-- FROM students WHERE first_name ILIKE '%a%'
--3/5. Fetch the students whose first_names start with the letter a.
-- SELECT first_name, last_name
-- FROM students WHERE first_name ILIKE 'a%'
--3/6. Fetch the students whose first_names end with the letter a.
-- SELECT first_name, last_name
-- FROM students WHERE first_name ILIKE '%a'
-- 3/7. Fetch the students whose second to last letter of their first_names are a (Example: Leah).
-- SELECT first_name, last_name
-- FROM students WHERE first_name ILIKE '%a_'
--3/8.  Fetch the students whose id’s are equal to 1 AND 3 .
-- SELECT first_name, last_name
-- FROM students WHERE students_id = 1 OR students_id = 3

-- 4. Fetch the students whose birth_dates are equal to or come after 1/01/2000. (show all their info).
SELECT * FROM students WHERE birth_date >= '1/01/2000'